name: build-images

on: push

jobs:
  lerna:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: |
          npm ci
          npm run build

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: '**'
          key: build-artifacts-${{ github.ref }}
  build:
    runs-on: ubuntu-latest
    needs: lerna
    steps:
      - name: Restore build artifacts
        uses: actions/cache@v2
        with:
          path: '**/dist'
          key: build-artifacts-${{ github.ref }}

      - name: Build GitHub Container Registry
        uses: ./.github/actions/build-images
        with:
          registry: 'ghcr.io'
          repository: '${{ github.repository }}'
          username: '${{ secrets.REGISTRY_USERNAME }}'
          password: '${{ secrets.REGISTRY_PASSWORD }}'
          version: '${{ github.ref }}'
          latest: 'true'
          push: 'true'

      - name: Build Docker Hub
        uses: ./.github/actions/build-images
        with:
          registry: 'docker.io'
          repository: '${{ github.repository }}'
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_PASSWORD }}'
          version: '${{ github.ref }}'
          latest: 'true'
          push: 'true'
