name: build-lerna

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: |
          npm ci
          npm run build

      - name: Cache build artifacts
        uses: actions/cache@v2
        env:
          cache-name: cache-build-artifacts
        with:
          path: '.'
          key: build-artifacts-${{ github.ref }}
