name: build-images

on: push

jobs:
  lerna:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - uses: c-hive/gha-npm-cache@v1
      - run: npm ci
      - run: npm run build
      - run: node docker/pack

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: '**/dist'
          key: build-artifacts-${{ github.hash }}
  build:
    runs-on: ubuntu-latest
    needs: lerna
    steps:
      - uses: actions/checkout@v2
      - name: Restore build artifacts
        uses: actions/cache@v2
        with:
          path: '**/dist'
          key: build-artifacts-${{ github.hash }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            directus/directus
            ghcr.io/cynova/directus
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      #- name: Login to DockerHub
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: './docker/Dockerfile'
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
